package monsters

import "github.com/koenic/rs-odds/pkg"

var All_Monsters = []pkg.Monster{
	AbyssalSire,
	AlchemicalHydra,
	Barrows,
	Bryophyta,
	CallistoAndArtio,
	Cerberus,
	ChambersOfXeric,
	ChaosElemental,
	ChaosFanatic,
	CommanderZilyana,
	CorporealBeast,
	CrazyArchaeologist,
	DagannothKings,
	DukeSucellus,
	FightCaves,
	Gauntlet,
	GeneralGraardor,
	GiantMole,
	GrotesqueGuardians,
	Hespori,
	Inferno,
	KRilTsutsaroth,
	KalphiteQueen,
	KingBlackDragon,
	Kraken,
	KreeArra,
	Leviathan,
	LizardmanShaman,
	MoonsOfPeril,
	Nex,
	Nightmare,
	NightmarePhosanis,
	Obor,
	PhantomMuspah,
	Sarachnis,
	Scorpia,
	Scurrius,
	Skotizo,
	Tempoross,
	TheatreOfBlood,
	TheatreOfBloodHardMode,
	ThermonuclearSmokeSevil,
	TombsOfAmascut,
	Vardorvis,
	VenenatisSpindel,
	VetIonCalvarIon,
	Vorkath,
	Whisperer,
	Wintertodt,
	Zalcano,
	Zulrah,
}
